# PiePieSpider.Content {#PiePieSpider-Content}

## RequestGetter

### Properties

| Usage | Description |
| ----- | ----------- |
| RequestGetter.IsRequestsGet | |
| RequestGetter.Text | |
| RequestGetter.Bytes | |

### Methods

| Usage | Description |
| ----- | ----------- |
| RequestGetter.Get(self) | |
| RequestGetter.Post(self, formData, verify = False) | |

## HtmlTextTools

### Class Methods

| Usage | Description |
| ----- | ----------- |
| HtmlTextTools.DropLineMark(cls, string: str) | |
| HtmlTextTools.DropReturnMark(cls, string: str) | |
| HtmlTextTools.DropTabMark(cls, string: str) | |
| HtmlTextTools.DropSpace(cls, string: str) | |
| HtmlTextTools.DropAllSpacing(cls, string: str) | |

## XmlParser

### Class Methods

| Usage | Description |
| ----- | ----------- |
| XmlParser.ElementTree(cls, html: str) | |
| XmlParserTryCatchXpath(cls, xml: lxml.etree._ElementTree, xpaths: list, index: int = 0) | |

## ReParser

### Class Methods

| Usage | Description |
| ----- | ----------- |
| ReParser.QuickMatch(cls, regExp: str, string: str, index = 0) | |

## BaseExtender

## BaseNetWalker

### Properties

| Usage | Description |
| ----- | ----------- |
| BaseNetWalker.Result | |
| BaseNetWalker.ErrorInfo | |
